# Generated by Django 3.2.6 on 2021-12-07 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20211206_1544'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
